In [5]:
import numpy as np

n1 = np.array([10,20, 30, 40, 50])
n2 = np.array([20, 30, 40, 50, 40])



In [16]:
np.vstack((n1, n2)) #to join elemnts vertical 

array([[10, 20, 30, 40, 50],
       [20, 30, 40, 50, 40]])

In [3]:
np.hstack((n1, n2)) #to join horizontal

array([10, 20, 30, 40, 50, 20, 30, 40, 50, 60,  7])

In [6]:
np.column_stack((n1, n2)) #to seperateley join column wise

array([[10, 20],
       [20, 30],
       [30, 40],
       [40, 50],
       [50, 40]])

In [7]:
#intersection & difference in numpy

np.intersect1d(n1, n2)


array([20, 30, 40, 50])

In [8]:
np.setdiff1d(n1,n2)

array([10])

In [9]:
np.setdiff1d(n2,n1)

array([], dtype=int32)

In [15]:
np.sum([n2, n1],axis = 1)

array([180, 150])

In [18]:
arr1 = np.array([10, 21, 22, 23, 24, 25])
arr2 = np.array([20, 31, 32, 33, 34, 35])
np.sum([arr1,arr2])

310

In [20]:
arr1 = np.array([10, 21, 22, 23, 24, 25])
arr2 = np.array([20, 31, 32, 33, 34, 35])
add =arr1*2
print(add)

[20 42 44 46 48 50]


In [22]:
arr3 = np.array([10, 21, 22, 23, 24, 25])
np.mean(arr3) #mean value

20.833333333333332

In [23]:
arr3 = np.array([10, 21, 22, 23, 24, 25])
np.median(arr3) #median

22.5

In [24]:
arr3 = np.array([10, 21, 22, 23, 24, 25])
np.std(arr3) #standard deviation


5.013869652163774